### ISSUE TITLE
S1 - As an unregistered user, I want to be able to register as a user with my chosen username and password. (Those are non-empty words.)

### ISSUE THREAD

**Issue by niklassc-xyz** [sopra-fs21-group-15/server#1]
- [x] Upon a successful user registration, the lobby screen is shown and the user is automatically logged in. 
- [x] Upon failure an error is displayed and the user is redirected to the register screen. (Possible error: The username is already taken.) 
- [x] Logged-in users can log out. 

**Priority**: critical 
**Author**: Group 15 
**Estimate**: 4h (already implemented in Milestone 1) 
**Category:** Registration

**Comment by Wahlbar** [comment]
Done! (Partly done in Milestone 1)
